//! Offline ISO country point-in-polygon for [`iso_at`].
//!
//! Geometry comes from the compiled Natural Earth Admin-0 asset generated by
//! `scripts/generate-country-polys.py` (see `data/ATTRIBUTION.txt`). Rings are
//! never hand-edited.
//!
//! Lookup: bounding-box grid index → exact ray-cast only for candidate
//! countries in the cell. Countries are stored smallest-area-first so overlaps
//! resolve deterministically. Coastal points that miss every polygon may snap
//! to the unique nearest country within [`COASTAL_SNAP_TOLERANCE_M`].

use std::sync::OnceLock;

/// Placeholder coastal snap distance (metres). Tunable.
pub const COASTAL_SNAP_TOLERANCE_M: f64 = 5_000.0;

/// Soft budget for the compiled asset (bytes). Tunable; enforced by the
/// generator script (`--max-bytes`).
pub const MAX_COUNTRY_POLYS_ASSET_BYTES: usize = 5 * 1024 * 1024;

/// Grid cell size in degrees for the spatial index. Tunable.
const GRID_CELL_DEG: f64 = 2.0;

const ASSET: &[u8] = include_bytes!("data/country_polys.bin");
const COORD_SCALE: f64 = 10_000_000.0;

#[derive(Clone)]
struct Ring {
    /// Closed ring as (lon, lat).
    pts: Vec<(f64, f64)>,
    min_lon: f64,
    min_lat: f64,
    max_lon: f64,
    max_lat: f64,
}

#[derive(Clone)]
struct Country {
    iso: [u8; 2],
    rings: Vec<Ring>,
    min_lon: f64,
    min_lat: f64,
    max_lon: f64,
    max_lat: f64,
}

struct Index {
    countries: Vec<Country>,
    /// Parallel to `countries`: leaked ISO strings for `'static` returns.
    iso_static: Vec<&'static str>,
    /// Cell → country indices that may cover the cell.
    cells: Vec<Vec<u16>>,
    origin_lon: f64,
    origin_lat: f64,
    n_lon: usize,
    n_lat: usize,
    cell_deg: f64,
}

fn decode_asset(bytes: &[u8]) -> Result<Vec<Country>, String> {
    if bytes.len() < 16 {
        return Err("asset too short".into());
    }
    if &bytes[0..8] != b"NAVICP50" {
        return Err("bad magic".into());
    }
    let version = u32::from_le_bytes(bytes[8..12].try_into().unwrap());
    if version != 1 {
        return Err(format!("unsupported version {version}"));
    }
    let n = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
    let mut off = 16;
    let mut countries = Vec::with_capacity(n);
    for _ in 0..n {
        if off + 8 > bytes.len() {
            return Err("truncated country header".into());
        }
        let iso = [bytes[off], bytes[off + 1]];
        if !iso[0].is_ascii_alphabetic() || !iso[1].is_ascii_alphabetic() {
            return Err(format!("bad iso {:?}", iso));
        }
        off += 4; // iso + pad
        let n_rings = u32::from_le_bytes(bytes[off..off + 4].try_into().unwrap()) as usize;
        off += 4;
        let mut rings = Vec::with_capacity(n_rings);
        let mut cmin_lon = f64::INFINITY;
        let mut cmin_lat = f64::INFINITY;
        let mut cmax_lon = f64::NEG_INFINITY;
        let mut cmax_lat = f64::NEG_INFINITY;
        for _ in 0..n_rings {
            if off + 4 > bytes.len() {
                return Err("truncated ring header".into());
            }
            let n_pts = u32::from_le_bytes(bytes[off..off + 4].try_into().unwrap()) as usize;
            off += 4;
            if off + n_pts * 8 > bytes.len() {
                return Err("truncated ring points".into());
            }
            let mut pts = Vec::with_capacity(n_pts);
            let mut rmin_lon = f64::INFINITY;
            let mut rmin_lat = f64::INFINITY;
            let mut rmax_lon = f64::NEG_INFINITY;
            let mut rmax_lat = f64::NEG_INFINITY;
            for _ in 0..n_pts {
                let lon_i = i32::from_le_bytes(bytes[off..off + 4].try_into().unwrap());
                let lat_i = i32::from_le_bytes(bytes[off + 4..off + 8].try_into().unwrap());
                off += 8;
                let lon = lon_i as f64 / COORD_SCALE;
                let lat = lat_i as f64 / COORD_SCALE;
                rmin_lon = rmin_lon.min(lon);
                rmin_lat = rmin_lat.min(lat);
                rmax_lon = rmax_lon.max(lon);
                rmax_lat = rmax_lat.max(lat);
                pts.push((lon, lat));
            }
            cmin_lon = cmin_lon.min(rmin_lon);
            cmin_lat = cmin_lat.min(rmin_lat);
            cmax_lon = cmax_lon.max(rmax_lon);
            cmax_lat = cmax_lat.max(rmax_lat);
            rings.push(Ring {
                pts,
                min_lon: rmin_lon,
                min_lat: rmin_lat,
                max_lon: rmax_lon,
                max_lat: rmax_lat,
            });
        }
        countries.push(Country {
            iso,
            rings,
            min_lon: cmin_lon,
            min_lat: cmin_lat,
            max_lon: cmax_lon,
            max_lat: cmax_lat,
        });
    }
    if off != bytes.len() {
        return Err(format!("trailing bytes: {} leftover", bytes.len() - off));
    }
    Ok(countries)
}

fn build_index(countries: Vec<Country>) -> Index {
    let mut iso_static = Vec::with_capacity(countries.len());
    for c in &countries {
        let s = String::from_utf8(c.iso.to_vec()).expect("ascii iso");
        iso_static.push(Box::leak(s.into_boxed_str()) as &'static str);
    }

    let mut min_lon = f64::INFINITY;
    let mut min_lat = f64::INFINITY;
    let mut max_lon = f64::NEG_INFINITY;
    let mut max_lat = f64::NEG_INFINITY;
    for c in &countries {
        min_lon = min_lon.min(c.min_lon);
        min_lat = min_lat.min(c.min_lat);
        max_lon = max_lon.max(c.max_lon);
        max_lat = max_lat.max(c.max_lat);
    }
    // Pad slightly so edge points fall inside the grid.
    min_lon -= GRID_CELL_DEG;
    min_lat -= GRID_CELL_DEG;
    max_lon += GRID_CELL_DEG;
    max_lat += GRID_CELL_DEG;

    let cell_deg = GRID_CELL_DEG;
    let n_lon = ((max_lon - min_lon) / cell_deg).ceil() as usize + 1;
    let n_lat = ((max_lat - min_lat) / cell_deg).ceil() as usize + 1;
    let mut cells = vec![Vec::<u16>::new(); n_lon * n_lat];

    for (ci, c) in countries.iter().enumerate() {
        let i0 = ((c.min_lon - min_lon) / cell_deg).floor().max(0.0) as usize;
        let i1 = ((c.max_lon - min_lon) / cell_deg)
            .floor()
            .min((n_lon - 1) as f64) as usize;
        let j0 = ((c.min_lat - min_lat) / cell_deg).floor().max(0.0) as usize;
        let j1 = ((c.max_lat - min_lat) / cell_deg)
            .floor()
            .min((n_lat - 1) as f64) as usize;
        for j in j0..=j1 {
            for i in i0..=i1 {
                cells[j * n_lon + i].push(ci as u16);
            }
        }
    }

    Index {
        countries,
        iso_static,
        cells,
        origin_lon: min_lon,
        origin_lat: min_lat,
        n_lon,
        n_lat,
        cell_deg,
    }
}

fn index() -> &'static Index {
    static IDX: OnceLock<Index> = OnceLock::new();
    IDX.get_or_init(|| {
        assert!(
            ASSET.len() <= MAX_COUNTRY_POLYS_ASSET_BYTES,
            "country polys asset {} exceeds budget {}",
            ASSET.len(),
            MAX_COUNTRY_POLYS_ASSET_BYTES
        );
        let countries = decode_asset(ASSET).expect("country_polys.bin decode");
        build_index(countries)
    })
}

fn cell_candidates(idx: &Index, lon: f64, lat: f64) -> &[u16] {
    let i = ((lon - idx.origin_lon) / idx.cell_deg).floor() as isize;
    let j = ((lat - idx.origin_lat) / idx.cell_deg).floor() as isize;
    if i < 0 || j < 0 || i as usize >= idx.n_lon || j as usize >= idx.n_lat {
        return &[];
    }
    &idx.cells[j as usize * idx.n_lon + i as usize]
}

fn point_in_ring(lon: f64, lat: f64, ring: &Ring) -> bool {
    if lon < ring.min_lon || lon > ring.max_lon || lat < ring.min_lat || lat > ring.max_lat {
        return false;
    }
    let pts = &ring.pts;
    let n = pts.len();
    if n < 3 {
        return false;
    }
    let mut inside = false;
    let mut j = n - 1;
    for i in 0..n {
        let (xi, yi) = pts[i];
        let (xj, yj) = pts[j];
        let intersect = ((yi > lat) != (yj > lat))
            && (lon < (xj - xi) * (lat - yi) / (yj - yi + f64::EPSILON) + xi);
        if intersect {
            inside = !inside;
        }
        j = i;
    }
    inside
}

fn point_in_country(c: &Country, lon: f64, lat: f64) -> bool {
    if lon < c.min_lon || lon > c.max_lon || lat < c.min_lat || lat > c.max_lat {
        return false;
    }
    // Shapefile-style: odd-even across all rings of the feature (islands + holes).
    let mut crossings = 0usize;
    for ring in &c.rings {
        if point_in_ring(lon, lat, ring) {
            crossings += 1;
        }
    }
    crossings % 2 == 1
}

fn dist_point_seg_m(lat: f64, lon: f64, lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    let latm = 111_320.0;
    let lonm = 111_320.0 * lat.to_radians().cos();
    let x = lon * lonm;
    let y = lat * latm;
    let x1 = lon1 * lonm;
    let y1 = lat1 * latm;
    let x2 = lon2 * lonm;
    let y2 = lat2 * latm;
    let dx = x2 - x1;
    let dy = y2 - y1;
    let len2 = dx * dx + dy * dy;
    if len2 < 1e-12 {
        let ex = x - x1;
        let ey = y - y1;
        return (ex * ex + ey * ey).sqrt();
    }
    let t = ((x - x1) * dx + (y - y1) * dy) / len2;
    let t = t.clamp(0.0, 1.0);
    let px = x1 + t * dx;
    let py = y1 + t * dy;
    let ex = x - px;
    let ey = y - py;
    (ex * ex + ey * ey).sqrt()
}

fn min_dist_to_country_m(c: &Country, lat: f64, lon: f64) -> f64 {
    let mut best = f64::INFINITY;
    for ring in &c.rings {
        let pts = &ring.pts;
        for i in 0..pts.len().saturating_sub(1) {
            let (lon1, lat1) = pts[i];
            let (lon2, lat2) = pts[i + 1];
            let d = dist_point_seg_m(lat, lon, lat1, lon1, lat2, lon2);
            if d < best {
                best = d;
            }
        }
    }
    best
}

/// Resolve ISO-3166-1 alpha-2 (lowercase) for a WGS84 point.
///
/// Determinism: countries are ordered by ascending polygon area at asset build
/// time; the first containing country wins. If none contain the point, snap to
/// the unique nearest country within [`COASTAL_SNAP_TOLERANCE_M`], else `None`.
pub fn iso_at(lat: f64, lon: f64) -> Option<&'static str> {
    let idx = index();
    let cands = cell_candidates(idx, lon, lat);
    // Exact PIP — first match wins (smallest area first in asset order).
    for &ci in cands {
        let c = &idx.countries[ci as usize];
        if point_in_country(c, lon, lat) {
            return Some(idx.iso_static[ci as usize]);
        }
    }
    // Coastal / fjord snap: unique nearest within tolerance.
    let tol = COASTAL_SNAP_TOLERANCE_M;
    let mut best_d = f64::INFINITY;
    let mut best_ci: Option<u16> = None;
    let mut ambiguous = false;
    // Search candidates in this cell plus a 1-cell neighbourhood for coast snap.
    let i = ((lon - idx.origin_lon) / idx.cell_deg).floor() as isize;
    let j = ((lat - idx.origin_lat) / idx.cell_deg).floor() as isize;
    let mut seen = vec![false; idx.countries.len()];
    for dj in -1..=1 {
        for di in -1..=1 {
            let ii = i + di;
            let jj = j + dj;
            if ii < 0 || jj < 0 || ii as usize >= idx.n_lon || jj as usize >= idx.n_lat {
                continue;
            }
            for &ci in &idx.cells[jj as usize * idx.n_lon + ii as usize] {
                let u = ci as usize;
                if seen[u] {
                    continue;
                }
                seen[u] = true;
                let c = &idx.countries[u];
                // Expand bbox by ~tol in degrees (~0.05° ≈ 5 km mid-lat).
                let pad = 0.1;
                if lon < c.min_lon - pad
                    || lon > c.max_lon + pad
                    || lat < c.min_lat - pad
                    || lat > c.max_lat + pad
                {
                    continue;
                }
                let d = min_dist_to_country_m(c, lat, lon);
                if d > tol {
                    continue;
                }
                if d + 25.0 < best_d {
                    best_d = d;
                    best_ci = Some(ci);
                    ambiguous = false;
                } else if (d - best_d).abs() <= 25.0 && best_ci.map(|b| b != ci).unwrap_or(false) {
                    ambiguous = true;
                }
            }
        }
    }
    if ambiguous {
        return None;
    }
    best_ci.map(|ci| idx.iso_static[ci as usize])
}


/// Distance in metres to the nearest border of a country other than `own_iso`.
/// Returns `0.0` when the point lies inside a foreign polygon (NE/OSM dispute).
pub fn dist_to_foreign_border_m(lat: f64, lon: f64, own_iso: &str) -> Option<f64> {
    let idx = index();
    let own = own_iso.to_ascii_lowercase();
    let mut best = f64::INFINITY;
    for (ci, c) in idx.countries.iter().enumerate() {
        if idx.iso_static[ci] == own {
            continue;
        }
        let pad = 3.0;
        if lon < c.min_lon - pad
            || lon > c.max_lon + pad
            || lat < c.min_lat - pad
            || lat > c.max_lat + pad
        {
            continue;
        }
        if point_in_country(c, lon, lat) {
            return Some(0.0);
        }
        let d = min_dist_to_country_m(c, lat, lon);
        if d < best {
            best = d;
        }
    }
    if best.is_finite() {
        Some(best)
    } else {
        None
    }
}

/// Force-load the polygon index and return approximate resident byte size of
/// decoded geometry (for memory measurements).
pub fn warm_country_polys() -> usize {
    let idx = index();
    let mut bytes = std::mem::size_of_val(idx);
    for c in &idx.countries {
        bytes += std::mem::size_of_val(c);
        for r in &c.rings {
            bytes += r.pts.len() * std::mem::size_of::<(f64, f64)>();
        }
    }
    for cell in &idx.cells {
        bytes += cell.len() * 2;
    }
    bytes
}

/// Number of countries in the loaded asset (after warm).
pub fn country_polys_count() -> usize {
    index().countries.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn asset_within_budget() {
        assert!(ASSET.len() <= MAX_COUNTRY_POLYS_ASSET_BYTES);
        assert!(ASSET.len() > 100_000, "asset unexpectedly tiny");
    }

    #[test]
    fn oslo_is_norway() {
        assert_eq!(iso_at(59.91, 10.75), Some("no"));
    }

    #[test]
    fn london_is_gb() {
        assert_eq!(iso_at(51.5074, -0.1278), Some("gb"));
    }

    #[test]
    fn kansas_is_us() {
        assert_eq!(iso_at(39.0, -98.0), Some("us"));
    }

    #[test]
    fn mid_atlantic_is_none() {
        assert_eq!(iso_at(35.0, -40.0), None);
    }

    #[test]
    fn liechtenstein_before_neighbours() {
        assert_eq!(iso_at(47.14, 9.52), Some("li"));
    }

    #[test]
    fn canada_and_mexico_present() {
        assert_eq!(iso_at(45.5, -75.7), Some("ca")); // Ottawa
        assert_eq!(iso_at(19.4, -99.1), Some("mx")); // Mexico City
    }

    #[test]
    fn kautokeino_is_norway_not_sweden() {
        assert_eq!(iso_at(69.0125, 23.0415), Some("no"));
    }

    #[test]
    fn flensburg_is_germany_not_denmark() {
        assert_eq!(iso_at(54.793, 9.433), Some("de"));
    }

    #[test]
    fn warm_reports_nonzero_memory() {
        let n = warm_country_polys();
        assert!(n > 100_000);
        assert!(country_polys_count() >= 35);
    }
}
