// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.navi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_navi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_navi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "navi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}














































































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is 
// rather `InterfaceTooLargeException`, caused by too many methods 
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib 
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
// 
// The `ffi_uniffi_contract_version` method and all checksum methods are put 
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_navi_checksum_func_apply_osm_update(
): Short
fun uniffi_navi_checksum_func_bind_geofabrik_region(
): Short
fun uniffi_navi_checksum_func_check_osm_updates(
): Short
fun uniffi_navi_checksum_func_delete_saved_route(
): Short
fun uniffi_navi_checksum_func_detected_parallelism(
): Short
fun uniffi_navi_checksum_func_eco_mode_default(
): Short
fun uniffi_navi_checksum_func_eco_mode_toggleable(
): Short
fun uniffi_navi_checksum_func_ensure_place_index(
): Short
fun uniffi_navi_checksum_func_ffi_linkage_smoke_test(
): Short
fun uniffi_navi_checksum_func_format_avoid_major_report(
): Short
fun uniffi_navi_checksum_func_last_gps_fix(
): Short
fun uniffi_navi_checksum_func_list_saved_routes(
): Short
fun uniffi_navi_checksum_func_load_vehicle_limits(
): Short
fun uniffi_navi_checksum_func_osm_update_staleness_days(
): Short
fun uniffi_navi_checksum_func_osm_weekly_reminder_due(
): Short
fun uniffi_navi_checksum_func_provision_region_data(
): Short
fun uniffi_navi_checksum_func_rasterize_icon_check(
): Short
fun uniffi_navi_checksum_func_rasterize_icon_png(
): Short
fun uniffi_navi_checksum_func_routing_worker_count(
): Short
fun uniffi_navi_checksum_func_run_car_corridor_pipeline(
): Short
fun uniffi_navi_checksum_func_run_car_corridor_smoke_test(
): Short
fun uniffi_navi_checksum_func_save_named_route(
): Short
fun uniffi_navi_checksum_func_save_vehicle_limits(
): Short
fun uniffi_navi_checksum_func_search_places(
): Short
fun uniffi_navi_checksum_func_set_osm_weekly_reminder(
): Short
fun uniffi_navi_checksum_func_travel_profile_menu_focus(
): Short
fun ffi_navi_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "navi"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is 
            // rather `InterfaceTooLargeException`, caused by too many methods 
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            // 
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since 
            // we already did that with `IntegrityCheckingUniffiLib` above.
            // Loading of library with integrity check done.
            lib
        }
        
    }

    // FFI functions
    fun uniffi_navi_fn_func_apply_osm_update(`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_bind_geofabrik_region(`dataDir`: RustBuffer.ByValue,`geofabrikRegion`: RustBuffer.ByValue,`pbfFilename`: RustBuffer.ByValue,`localSequence`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_check_osm_updates(`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_delete_saved_route(`dataDir`: RustBuffer.ByValue,`id`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_navi_fn_func_detected_parallelism(uniffi_out_err: UniffiRustCallStatus, 
): Int
fun uniffi_navi_fn_func_eco_mode_default(`profile`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_navi_fn_func_eco_mode_toggleable(`profile`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_navi_fn_func_ensure_place_index(`pbfPath`: RustBuffer.ByValue,`indexDbPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_ffi_linkage_smoke_test(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_format_avoid_major_report(`avoidMajor`: Byte,`priorityPathSharePct`: Double,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_last_gps_fix(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_list_saved_routes(`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_load_vehicle_limits(`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_osm_update_staleness_days(uniffi_out_err: UniffiRustCallStatus, 
): Long
fun uniffi_navi_fn_func_osm_weekly_reminder_due(`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_navi_fn_func_provision_region_data(`dataDir`: RustBuffer.ByValue,`pbfUrl`: RustBuffer.ByValue,`pbfFilename`: RustBuffer.ByValue,`elevationTarUrl`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_rasterize_icon_check(`key`: RustBuffer.ByValue,`theme`: RustBuffer.ByValue,`width`: Int,`height`: Int,`bundledDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_rasterize_icon_png(`key`: RustBuffer.ByValue,`theme`: RustBuffer.ByValue,`width`: Int,`height`: Int,`bundledDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_routing_worker_count(uniffi_out_err: UniffiRustCallStatus, 
): Int
fun uniffi_navi_fn_func_run_car_corridor_pipeline(`pbfPath`: RustBuffer.ByValue,`elevDir`: RustBuffer.ByValue,`cacheDir`: RustBuffer.ByValue,`breakIntervalHours`: Double,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_run_car_corridor_smoke_test(`pbfPath`: RustBuffer.ByValue,`elevDir`: RustBuffer.ByValue,`breakIntervalHours`: Double,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_save_named_route(`dataDir`: RustBuffer.ByValue,`startLat`: Double,`startLon`: Double,`startName`: RustBuffer.ByValue,`endLat`: Double,`endLon`: Double,`endName`: RustBuffer.ByValue,`viaJson`: RustBuffer.ByValue,`profile`: RustBuffer.ByValue,`summaryJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_save_vehicle_limits(`dataDir`: RustBuffer.ByValue,`limits`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_navi_fn_func_search_places(`indexDbPath`: RustBuffer.ByValue,`query`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_navi_fn_func_set_osm_weekly_reminder(`dataDir`: RustBuffer.ByValue,`enabled`: Byte,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun uniffi_navi_fn_func_travel_profile_menu_focus(`profile`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_navi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_navi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_navi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_navi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_navi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_navi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_navi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_navi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_navi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_navi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_navi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_navi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_navi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
fun ffi_navi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_navi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun ffi_navi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_navi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_navi_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_navi_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_navi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_navi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_navi_checksum_func_apply_osm_update() != 13642.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_bind_geofabrik_region() != 54334.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_check_osm_updates() != 15834.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_delete_saved_route() != 15986.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_detected_parallelism() != 47010.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_eco_mode_default() != 51756.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_eco_mode_toggleable() != 50686.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_ensure_place_index() != 50894.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_ffi_linkage_smoke_test() != 11010.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_format_avoid_major_report() != 62066.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_last_gps_fix() != 42347.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_list_saved_routes() != 35027.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_load_vehicle_limits() != 31229.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_osm_update_staleness_days() != 60003.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_osm_weekly_reminder_due() != 61589.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_provision_region_data() != 5529.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_rasterize_icon_check() != 64066.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_rasterize_icon_png() != 19569.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_routing_worker_count() != 4016.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_run_car_corridor_pipeline() != 8479.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_run_car_corridor_smoke_test() != 48155.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_save_named_route() != 29751.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_save_vehicle_limits() != 61328.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_search_places() != 16235.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_set_osm_weekly_reminder() != 51186.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_navi_checksum_func_travel_profile_menu_focus() != 46717.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class CorridorRouteResult (
    var `report`: kotlin.String, 
    var `distanceKm`: kotlin.Double, 
    var `cacheHit`: kotlin.Boolean, 
    var `coldBuildS`: kotlin.Double, 
    var `warmLoadS`: kotlin.Double, 
    /**
     * Encoded as "lon,lat;lon,lat;..." (MapLibre GeoJSON built on the Kotlin side).
     */
    var `routePolyline`: kotlin.String, 
    var `poiLat`: kotlin.Double, 
    var `poiLon`: kotlin.Double, 
    var `poiName`: kotlin.String, 
    var `poiIconKey`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCorridorRouteResult: FfiConverterRustBuffer<CorridorRouteResult> {
    override fun read(buf: ByteBuffer): CorridorRouteResult {
        return CorridorRouteResult(
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: CorridorRouteResult) = (
            FfiConverterString.allocationSize(value.`report`) +
            FfiConverterDouble.allocationSize(value.`distanceKm`) +
            FfiConverterBoolean.allocationSize(value.`cacheHit`) +
            FfiConverterDouble.allocationSize(value.`coldBuildS`) +
            FfiConverterDouble.allocationSize(value.`warmLoadS`) +
            FfiConverterString.allocationSize(value.`routePolyline`) +
            FfiConverterDouble.allocationSize(value.`poiLat`) +
            FfiConverterDouble.allocationSize(value.`poiLon`) +
            FfiConverterString.allocationSize(value.`poiName`) +
            FfiConverterString.allocationSize(value.`poiIconKey`)
    )

    override fun write(value: CorridorRouteResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`report`, buf)
            FfiConverterDouble.write(value.`distanceKm`, buf)
            FfiConverterBoolean.write(value.`cacheHit`, buf)
            FfiConverterDouble.write(value.`coldBuildS`, buf)
            FfiConverterDouble.write(value.`warmLoadS`, buf)
            FfiConverterString.write(value.`routePolyline`, buf)
            FfiConverterDouble.write(value.`poiLat`, buf)
            FfiConverterDouble.write(value.`poiLon`, buf)
            FfiConverterString.write(value.`poiName`, buf)
            FfiConverterString.write(value.`poiIconKey`, buf)
    }
}



data class FfiGpsFix (
    var `lat`: kotlin.Double, 
    var `lon`: kotlin.Double, 
    var `available`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiGpsFix: FfiConverterRustBuffer<FfiGpsFix> {
    override fun read(buf: ByteBuffer): FfiGpsFix {
        return FfiGpsFix(
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: FfiGpsFix) = (
            FfiConverterDouble.allocationSize(value.`lat`) +
            FfiConverterDouble.allocationSize(value.`lon`) +
            FfiConverterBoolean.allocationSize(value.`available`)
    )

    override fun write(value: FfiGpsFix, buf: ByteBuffer) {
            FfiConverterDouble.write(value.`lat`, buf)
            FfiConverterDouble.write(value.`lon`, buf)
            FfiConverterBoolean.write(value.`available`, buf)
    }
}



data class FfiSavedRoute (
    var `id`: kotlin.String, 
    var `startName`: kotlin.String, 
    var `endName`: kotlin.String, 
    var `profile`: kotlin.String, 
    var `createdAt`: kotlin.String, 
    var `startLat`: kotlin.Double, 
    var `startLon`: kotlin.Double, 
    var `endLat`: kotlin.Double, 
    var `endLon`: kotlin.Double, 
    var `lastBreakLat`: kotlin.Double?, 
    var `lastBreakLon`: kotlin.Double?, 
    var `summaryJson`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiSavedRoute: FfiConverterRustBuffer<FfiSavedRoute> {
    override fun read(buf: ByteBuffer): FfiSavedRoute {
        return FfiSavedRoute(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiSavedRoute) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`startName`) +
            FfiConverterString.allocationSize(value.`endName`) +
            FfiConverterString.allocationSize(value.`profile`) +
            FfiConverterString.allocationSize(value.`createdAt`) +
            FfiConverterDouble.allocationSize(value.`startLat`) +
            FfiConverterDouble.allocationSize(value.`startLon`) +
            FfiConverterDouble.allocationSize(value.`endLat`) +
            FfiConverterDouble.allocationSize(value.`endLon`) +
            FfiConverterOptionalDouble.allocationSize(value.`lastBreakLat`) +
            FfiConverterOptionalDouble.allocationSize(value.`lastBreakLon`) +
            FfiConverterString.allocationSize(value.`summaryJson`)
    )

    override fun write(value: FfiSavedRoute, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`startName`, buf)
            FfiConverterString.write(value.`endName`, buf)
            FfiConverterString.write(value.`profile`, buf)
            FfiConverterString.write(value.`createdAt`, buf)
            FfiConverterDouble.write(value.`startLat`, buf)
            FfiConverterDouble.write(value.`startLon`, buf)
            FfiConverterDouble.write(value.`endLat`, buf)
            FfiConverterDouble.write(value.`endLon`, buf)
            FfiConverterOptionalDouble.write(value.`lastBreakLat`, buf)
            FfiConverterOptionalDouble.write(value.`lastBreakLon`, buf)
            FfiConverterString.write(value.`summaryJson`, buf)
    }
}



data class FfiVehicleLimits (
    var `axleWeightKg`: kotlin.Double?, 
    var `heightM`: kotlin.Double?, 
    var `widthM`: kotlin.Double?, 
    var `totalWeightKg`: kotlin.Double?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiVehicleLimits: FfiConverterRustBuffer<FfiVehicleLimits> {
    override fun read(buf: ByteBuffer): FfiVehicleLimits {
        return FfiVehicleLimits(
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
        )
    }

    override fun allocationSize(value: FfiVehicleLimits) = (
            FfiConverterOptionalDouble.allocationSize(value.`axleWeightKg`) +
            FfiConverterOptionalDouble.allocationSize(value.`heightM`) +
            FfiConverterOptionalDouble.allocationSize(value.`widthM`) +
            FfiConverterOptionalDouble.allocationSize(value.`totalWeightKg`)
    )

    override fun write(value: FfiVehicleLimits, buf: ByteBuffer) {
            FfiConverterOptionalDouble.write(value.`axleWeightKg`, buf)
            FfiConverterOptionalDouble.write(value.`heightM`, buf)
            FfiConverterOptionalDouble.write(value.`widthM`, buf)
            FfiConverterOptionalDouble.write(value.`totalWeightKg`, buf)
    }
}



data class PlaceHit (
    var `osmId`: kotlin.Long, 
    var `name`: kotlin.String, 
    var `kind`: kotlin.String, 
    var `lat`: kotlin.Double, 
    var `lon`: kotlin.Double
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePlaceHit: FfiConverterRustBuffer<PlaceHit> {
    override fun read(buf: ByteBuffer): PlaceHit {
        return PlaceHit(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: PlaceHit) = (
            FfiConverterLong.allocationSize(value.`osmId`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`kind`) +
            FfiConverterDouble.allocationSize(value.`lat`) +
            FfiConverterDouble.allocationSize(value.`lon`)
    )

    override fun write(value: PlaceHit, buf: ByteBuffer) {
            FfiConverterLong.write(value.`osmId`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`kind`, buf)
            FfiConverterDouble.write(value.`lat`, buf)
            FfiConverterDouble.write(value.`lon`, buf)
    }
}




enum class FfiIconTheme {
    
    DAY,
    NIGHT;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiIconTheme: FfiConverterRustBuffer<FfiIconTheme> {
    override fun read(buf: ByteBuffer) = try {
        FfiIconTheme.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiIconTheme) = 4UL

    override fun write(value: FfiIconTheme, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class TravelProfile {
    
    CAR,
    CAR_ELECTRIC,
    TRUCK,
    TRUCK_ELECTRIC,
    BICYCLE,
    HIKING,
    MOTORCYCLE,
    MOTORCYCLE_ELECTRIC;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeTravelProfile: FfiConverterRustBuffer<TravelProfile> {
    override fun read(buf: ByteBuffer) = try {
        TravelProfile.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: TravelProfile) = 4UL

    override fun write(value: TravelProfile, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalDouble: FfiConverterRustBuffer<kotlin.Double?> {
    override fun read(buf: ByteBuffer): kotlin.Double? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterDouble.read(buf)
    }

    override fun allocationSize(value: kotlin.Double?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterDouble.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Double?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterDouble.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiSavedRoute: FfiConverterRustBuffer<List<FfiSavedRoute>> {
    override fun read(buf: ByteBuffer): List<FfiSavedRoute> {
        val len = buf.getInt()
        return List<FfiSavedRoute>(len) {
            FfiConverterTypeFfiSavedRoute.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiSavedRoute>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiSavedRoute.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiSavedRoute>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiSavedRoute.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePlaceHit: FfiConverterRustBuffer<List<PlaceHit>> {
    override fun read(buf: ByteBuffer): List<PlaceHit> {
        val len = buf.getInt()
        return List<PlaceHit>(len) {
            FfiConverterTypePlaceHit.read(buf)
        }
    }

    override fun allocationSize(value: List<PlaceHit>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePlaceHit.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PlaceHit>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePlaceHit.write(it, buf)
        }
    }
}
        /**
         * Apply the pending plan from the last check (user-confirmed).
         */ fun `applyOsmUpdate`(`dataDir`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_apply_osm_update(
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    

        /**
         * Bind a Geofabrik region to the local extract (required before update checks).
         */ fun `bindGeofabrikRegion`(`dataDir`: kotlin.String, `geofabrikRegion`: kotlin.String, `pbfFilename`: kotlin.String, `localSequence`: kotlin.ULong?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_bind_geofabrik_region(
        FfiConverterString.lower(`dataDir`),FfiConverterString.lower(`geofabrikRegion`),FfiConverterString.lower(`pbfFilename`),FfiConverterOptionalULong.lower(`localSequence`),_status)
}
    )
    }
    

        /**
         * Opt-in OSM update check against Geofabrik (never downloads map data by itself).
         */ fun `checkOsmUpdates`(`dataDir`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_check_osm_updates(
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    
 fun `deleteSavedRoute`(`dataDir`: kotlin.String, `id`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_delete_saved_route(
        FfiConverterString.lower(`dataDir`),FfiConverterString.lower(`id`),_status)
}
    )
    }
    

        /**
         * Number of logical CPU cores detected on the host (routing worker autodetect input).
         */ fun `detectedParallelism`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_detected_parallelism(
        _status)
}
    )
    }
    

        /**
         * Default eco enabled for profile.
         */ fun `ecoModeDefault`(`profile`: TravelProfile): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_eco_mode_default(
        FfiConverterTypeTravelProfile.lower(`profile`),_status)
}
    )
    }
    

        /**
         * Whether eco-mode is user-toggleable for this profile (Hiking/Cycling default on / locked).
         */ fun `ecoModeToggleable`(`profile`: TravelProfile): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_eco_mode_toggleable(
        FfiConverterTypeTravelProfile.lower(`profile`),_status)
}
    )
    }
    

        /**
         * Build or open the offline FTS name index for a region PBF.
         * Returns number of indexed named features (0 on failure; check report string).
         */ fun `ensurePlaceIndex`(`pbfPath`: kotlin.String, `indexDbPath`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_ensure_place_index(
        FfiConverterString.lower(`pbfPath`),FfiConverterString.lower(`indexDbPath`),_status)
}
    )
    }
    

        /**
         * Fast FFI/worker-pool smoke test. Does **not** validate routing.
         *
         * Report always contains `TEST_KIND=SMOKE` and `DATA_SOURCE=none`.
         */ fun `ffiLinkageSmokeTest`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_ffi_linkage_smoke_test(
        _status)
}
    )
    }
    

        /**
         * Format a short validation blurb for avoid-major-roads / priority-path share.
         */ fun `formatAvoidMajorReport`(`avoidMajor`: kotlin.Boolean, `priorityPathSharePct`: kotlin.Double): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_format_avoid_major_report(
        FfiConverterBoolean.lower(`avoidMajor`),FfiConverterDouble.lower(`priorityPathSharePct`),_status)
}
    )
    }
    

        /**
         * Stub GPS fix for UI actions until Android fused location is wired.
         */ fun `lastGpsFix`(): FfiGpsFix {
            return FfiConverterTypeFfiGpsFix.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_last_gps_fix(
        _status)
}
    )
    }
    
 fun `listSavedRoutes`(`dataDir`: kotlin.String): List<FfiSavedRoute> {
            return FfiConverterSequenceTypeFfiSavedRoute.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_list_saved_routes(
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    
 fun `loadVehicleLimits`(`dataDir`: kotlin.String): FfiVehicleLimits {
            return FfiConverterTypeFfiVehicleLimits.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_load_vehicle_limits(
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    
 fun `osmUpdateStalenessDays`(): kotlin.ULong {
            return FfiConverterULong.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_osm_update_staleness_days(
        _status)
}
    )
    }
    
 fun `osmWeeklyReminderDue`(`dataDir`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_osm_weekly_reminder_due(
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    

        /**
         * Download / ensure region data under `data_dir` via the in-app provisioner.
         *
         * `pbf_url` is typically `http://10.0.2.2:<port>/...` from the emulator.
         * Optional `elevation_tar_url` seeds DEM tiles without live Copernicus fetch.
         */ fun `provisionRegionData`(`dataDir`: kotlin.String, `pbfUrl`: kotlin.String, `pbfFilename`: kotlin.String, `elevationTarUrl`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_provision_region_data(
        FfiConverterString.lower(`dataDir`),FfiConverterString.lower(`pbfUrl`),FfiConverterString.lower(`pbfFilename`),FfiConverterOptionalString.lower(`elevationTarUrl`),_status)
}
    )
    }
    

        /**
         * Rasterize and return a short status string for instrumented tests.
         */ fun `rasterizeIconCheck`(`key`: kotlin.String, `theme`: FfiIconTheme, `width`: kotlin.UInt, `height`: kotlin.UInt, `bundledDir`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_rasterize_icon_check(
        FfiConverterString.lower(`key`),FfiConverterTypeFfiIconTheme.lower(`theme`),FfiConverterUInt.lower(`width`),FfiConverterUInt.lower(`height`),FfiConverterString.lower(`bundledDir`),_status)
}
    )
    }
    

        /**
         * Rasterize a semantic icon to PNG bytes (real usvg/resvg pipeline).
         */ fun `rasterizeIconPng`(`key`: kotlin.String, `theme`: FfiIconTheme, `width`: kotlin.UInt, `height`: kotlin.UInt, `bundledDir`: kotlin.String): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_rasterize_icon_png(
        FfiConverterString.lower(`key`),FfiConverterTypeFfiIconTheme.lower(`theme`),FfiConverterUInt.lower(`width`),FfiConverterUInt.lower(`height`),FfiConverterString.lower(`bundledDir`),_status)
}
    )
    }
    

        /**
         * Routing-tier worker count after reserving UI/audio headroom.
         */ fun `routingWorkerCount`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_routing_worker_count(
        _status)
}
    )
    }
    

        /**
         * Real on-device corridor pipeline (Espa -> Atnbrufossen).
         *
         * Requires a real OSM `.pbf` already present (use [`provision_region_data`] first).
         * Runs the pipeline twice to assert graph-cache speedup. Report always includes
         * `TEST_KIND=REAL_PIPELINE` and `DATA_SOURCE=real_pbf`.
         */ fun `runCarCorridorPipeline`(`pbfPath`: kotlin.String, `elevDir`: kotlin.String, `cacheDir`: kotlin.String, `breakIntervalHours`: kotlin.Double): CorridorRouteResult {
            return FfiConverterTypeCorridorRouteResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_run_car_corridor_pipeline(
        FfiConverterString.lower(`pbfPath`),FfiConverterString.lower(`elevDir`),FfiConverterString.lower(`cacheDir`),FfiConverterDouble.lower(`breakIntervalHours`),_status)
}
    )
    }
    

        /**
         * Backward-compatible wrapper: real pipeline without separate cache dir (uses elev parent).
         */ fun `runCarCorridorSmokeTest`(`pbfPath`: kotlin.String, `elevDir`: kotlin.String, `breakIntervalHours`: kotlin.Double): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_run_car_corridor_smoke_test(
        FfiConverterString.lower(`pbfPath`),FfiConverterString.lower(`elevDir`),FfiConverterDouble.lower(`breakIntervalHours`),_status)
}
    )
    }
    
 fun `saveNamedRoute`(`dataDir`: kotlin.String, `startLat`: kotlin.Double, `startLon`: kotlin.Double, `startName`: kotlin.String, `endLat`: kotlin.Double, `endLon`: kotlin.Double, `endName`: kotlin.String, `viaJson`: kotlin.String, `profile`: kotlin.String, `summaryJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_save_named_route(
        FfiConverterString.lower(`dataDir`),FfiConverterDouble.lower(`startLat`),FfiConverterDouble.lower(`startLon`),FfiConverterString.lower(`startName`),FfiConverterDouble.lower(`endLat`),FfiConverterDouble.lower(`endLon`),FfiConverterString.lower(`endName`),FfiConverterString.lower(`viaJson`),FfiConverterString.lower(`profile`),FfiConverterString.lower(`summaryJson`),_status)
}
    )
    }
    
 fun `saveVehicleLimits`(`dataDir`: kotlin.String, `limits`: FfiVehicleLimits): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_save_vehicle_limits(
        FfiConverterString.lower(`dataDir`),FfiConverterTypeFfiVehicleLimits.lower(`limits`),_status)
}
    )
    }
    

        /**
         * Offline place / address-style name search (FTS5 prefix).
         */ fun `searchPlaces`(`indexDbPath`: kotlin.String, `query`: kotlin.String, `limit`: kotlin.UInt): List<PlaceHit> {
            return FfiConverterSequenceTypePlaceHit.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_search_places(
        FfiConverterString.lower(`indexDbPath`),FfiConverterString.lower(`query`),FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    

        /**
         * Weekly reminder opt-in (surfaces a check prompt; never auto-applies).
         */ fun `setOsmWeeklyReminder`(`dataDir`: kotlin.String, `enabled`: kotlin.Boolean): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_set_osm_weekly_reminder(
        FfiConverterString.lower(`dataDir`),FfiConverterBoolean.lower(`enabled`),_status)
}
    )
    }
    

        /**
         * Whether this profile appears as a primary travel-mode chip.
         */ fun `travelProfileMenuFocus`(`profile`: TravelProfile): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_navi_fn_func_travel_profile_menu_focus(
        FfiConverterTypeTravelProfile.lower(`profile`),_status)
}
    )
    }
    


